[package]
name = "few"
version = "0.1.0"
authors = ["Rabbit <yfhj1990@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
